# Generated by Django 4.1.3 on 2022-11-08 03:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="ordered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="ordered_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="product_lines",
            field=models.ManyToManyField(to="core.orderlines"),
        ),
        migrations.AddField(
            model_name="order",
            name="start_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("shirt", "SHIRT"),
                    ("sport_wear", "SPORT WEAR"),
                    ("outwear", "OUTWEAR"),
                ],
                default="shirt",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(default="test description"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="discount_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="label",
            field=models.CharField(
                choices=[("P", "primary"), ("S", "secondary"), ("D", "danger")],
                default="P",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default="slug-product-1"),
            preserve_default=False,
        ),
    ]
