# Generated by Django 4.1.3 on 2022-11-08 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_order_ordered_order_ordered_date_order_product_lines_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlines",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
