# Generated by Django 4.1.3 on 2022-11-08 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_orderlines_quantity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="product_lines",
            new_name="order_lines",
        ),
    ]
