# Generated by Django 4.1.3 on 2022-11-08 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_product_lines_order_order_lines"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderlines",
            old_name="item_id",
            new_name="product_id",
        ),
    ]
